"""reset migration with enum

Revision ID: b06227eb9b54
Revises: 
Create Date: 2026-01-09 20:03:42.650565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06227eb9b54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. KHAI BÁO ENUM
    # Lưu ý: Thứ tự các giá trị nên khớp với Enum trong code Python
    clinic_status_enum = sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='clinicstatus')
    
    # 2. TẠO TYPE TRONG DB (Đây là bước Alembic bị thiếu)
    clinic_status_enum.create(op.get_bind(), checkfirst=True)

    # 3. THÊM CỘT
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinics', sa.Column('status', clinic_status_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinics', 'status')
    # ### end Alembic commands ###
    
    # XÓA TYPE KHI DOWNGRADE (Để sạch database)
    clinic_status_enum = sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='clinicstatus')
    clinic_status_enum.drop(op.get_bind(), checkfirst=True)